#!/bin/bash
let error_status=0
declare -a subholder
declare -a allcommands=(--directories --commands-for-deleted --commands-for-new --commands-for-changed)
declare -a delete_commands
dieformat()
{
  if [ -t 2 ];then
    echo -ne "\033[4;31mERROR\033[0m: " >&2
  else
    echo -ne "ERROR: " >&2
  fi
  if [ $# -gt 0 ];then
    echo "$*" >&2
  fi
}
infoformat()
{
  if [ -t 2 ];then
    echo -ne "\033[4;32mINFO\033[0m: " >&2
  else
    echo -ne "INFO: " >&2
  fi
  if [ $# -gt 0 ];then
    echo "$*" >&2
  fi
}
die()
{
  let error_status++
  dieformat "$@"
  exit $error_status
}

cleanup_with_errors()
{
  die "cwatch: an error has occured...aborting"
}

cleanup_exit()
{
  if [ -p "/tmp/cwatch-nosub" ];then
    rm -f "/tmp/cwatch-nosub" > /dev/null 2>&1
  fi
  exec 3>&-
  exit $error_status
}
trap cleanup_with_errors SIGHUP SIGTERM SIGINT SIGPIPE
trap cleanup_exit EXIT

iscommand()
{
  if [ $# -eq 0 ];then
    return 1
  elif [ $# -gt 1 ];then
    die "one command at a time"
  fi
  for ca in "${allcommands[@]}";do
    if [ "$ca" == "$1" ];then
      return 0
    fi
  done
  return 1
}
parse_file_path()
{
  parsed_directory_path=
  parsed_file_path=
  parsed_file_name=
  if [ -z "$1" ];then
    return 1
  elif [ "$#" -gt 1 ];then
    return 1
  fi
  local file="$1"
  shift
  parsed_directory_path="${file%/*}"
  parsed_file_path="${file%.*}"
  parsed_file_name="${parsed_file_path##*/}"
  return 0
}

dep(){
  dep_result=
  if [ -z "$1" ];then
    return 1
  fi
  if [ -p "/tmp/cwatch-nosub" ];then
    rm -f "/tmp/cwatch-nosub" > /dev/null 2>&1
    exec 3>&-
  fi
  mkfifo "/tmp/cwatch-nosub" > /dev/null 2>&1
  if [ ! -p "/tmp/cwatch-nosub" ];then
    die "could not create pipe"
  fi
  exec 3<> "/tmp/cwatch-nosub"
  if which "$1" 2> /dev/null 1>&3;then
    read -u3 dep_result
    exec 3>&-
    rm -f "/tmp/cwatch-nosub" > /dev/null 2>&1
    return 0
  fi
  return 1
}
sub()
{
  sub_result=
  if [ $# -eq 0 ];then
    return 1
  fi
  unset subholder
  while (( $# ));do
    subholder+=("$1")
    shift
  done
  if [ ! -p "/tmp/cwatch-nosub" ];then
    mkfifo "/tmp/cwatch-nosub" > /dev/null 2>&1
    if [ ! -p "/tmp/cwatch-nosub" ];then
      die "could not create pipe"
    fi
    exec 3<> "/tmp/cwatch-nosub"
  fi
  if "${subholder[@]}" 2> /dev/null  1>&3;then
    read -u3 sub_result
    return 0
  fi
  return 1
}

#if sub cat ~/Desktop/hello.txt;then
#  echo "$sub_result"
#fi

#directories to watch
declare -a directories
if dep 'binbuild';then
  BIN_BUILD="$dep_result"
fi
lock_dir="$HOME/.watch-lock"
if [ ! -d "$lock_dir" ];then
  mkdir -p "$lock_dir" > /dev/null 2>&1
  if [ ! -d "$lock_dir" ];then
    echo "ERROR: cannot create a lock"
    exit 1
  fi
fi

while (( $# ));do
  if [ -z "$1" ];then
    die "cannot use empty params"
  elif [ "$1" == '--directories' ];then
    shift
    if [ -z "$1" ];then
      die "no values entered for directories"
    fi
    while (( $# ));do
      if [ -z "$1" ];then
	die "cannot use empty params"
      elif iscommand "$1";then
	break
      elif [ ! -d "$1" ];then
	die "$1 is not a directory"
      else
	if [ "$1" == '.' ];then
	  directories+=("$PWD")
	else
	  directories+=("$1");
	fi
	shift
      fi
    done
  elif [ "$1" == '--commands-for-deleted' ];then
    shift
    if [ -z "$1" ];then
      die "no values entered for deleted commands"
    fi
    while (( $# ));do
      if [ -z "$1" ];then
	die "cannot use empty params"
      elif iscommand "$1";then
	break
      elif ! dep "$1";then
	die "$1 is not a valid command"
      else
	delete_commands+=("$1")
	shift
      fi
    done
  else
    die "invalid command $1"
  fi
done

if [ "${#directories[@]}" -eq 0 ];then
  directories+=("$PWD")
fi
infoformat "watching directories: ${directories[@]}"
let running=1
last_modified=
previous_modified=
if ! which stat > /dev/null 2>&1;then
  echo "ERROR: dependency stat not installed"
  exit 1
fi
while (( "$running" ));do
  for directory in "${directories[@]}";do
    if [ -d "$directory" ];then
      for file in "$directory"/*;do
	if [ -e "$file" ];then
	  if ! parse_file_path "$file";then
	    die "could not parse file path"
	  fi
	  if sub stat -f "%Sm" -t %s "$file";then
	    last_modified="$sub_result"
	  else
	    die "could not get modified date"
	  fi
	  #last_modified=$(stat -f "%Sm" -t %s $file 2> /dev/null)
	  if [ -z "$last_modified" ];then
	    let last_modified=0
	  fi
	  if [ ! -d "$lock_dir/$parsed_directory_path" ];then
	    mkdir -p "$lock_dir/$parsed_directory_path" > /dev/null 2>&1
	    if [ ! -d "$lock_dir/$parsed_directory_path" ];then
	      die "could not create lock directory"
	    fi
	  fi
	  if [ ! -f "$lock_dir/$parsed_file_path.mod" ];then
	    echo "$last_modified" > "$lock_dir/$parsed_file_path.mod"
	    echo "$file" > "$lock_dir/$parsed_file_path.dest"
	    echo "new file -> $file"
	  else
	    if sub cat "$lock_dir/$parsed_file_path.mod";then
	      previous_modified="$sub_result"
	    else
	      die "could not read lock date"
	    fi
	    #previous_modified=$(cat "$lock_dir/$name.mod")
	    let mod_diff=$((last_modified - previous_modified))
	    if [ $mod_diff -gt 0 ];then
	      echo "changed -> $file"
	    fi
	    echo "$last_modified" > "$lock_dir/$parsed_file_path.mod"
	  fi
	fi
      done
    fi
  done
  #check deleted
  #  for lock_dest in "$lock_dir"/*.dest;do
  #    if [ -f "$lock_dest" ];then
  #      if sub cat "$lock_dest";then
  #	dest="$sub_result"
  #      else
  #	die "could not get dest file"
  #      fi
  #      #dest=$(cat "$lock_dest")
  #      if [ ! -e "$dest" ];then
  #	
  #	name="${lock_dest##*/}"
  #	name="${name%.*}"
  #	if parse_file_path "$lock_dest";then
  #	  rm -f "$parsed_file_path.mod"
  #	  rm -f "$parsed_file_path.dest"
  #	fi
  #	echo "deleted -> $dest"
  #	#rm -f "$lock_dest" > /dev/null 2>&1
  #	#rm -f "$lock_dir/$name.mod" > /dev/null 2>&1
  #	#run deleted commands
  #	for delcom in "${delete_commands[@]}";do
  #	  infoformat "running $delcom"
  #	done
  #      fi
  #    fi
  #  done
done
