#!/bin/bash
#TODO
while (( $# ));do
  if [ -z "$1" ];then
    echo "ERROR: cannot use empty params"
  fi
  shift
done
declare -a objects
INC="$PWD/include"
SRC="$PWD/src"
BUILD="$PWD/build"
LIB="$PWD/lib"
source_files="$SRC"/*.c
object_files="$BUILD"/*.o
libname="${PWD##*/}"
soname="lib$libname.so.1"
outputname="lib$libname.so.1.0.1"
linkername="lib$libname.so"
CURR_USER=$(whoami)
LIB_INSTALL_DIR="/usr/local/lib"
INCLUDE_INSTALL_DIR="/usr/local/include"

if [ -z "$CURR_USER" ];then
  echo "cannot get current user"
  exit 1
elif [ "$CURR_USER" != 'root' ];then
  echo "user must be root, got $CURR_USER"
  exit 1
fi

if [ ! -d "$INC" ];then
  mkdir -p "$INC"
fi
if [ ! -d "$SRC" ];then
  mkdir -p "$SRC"
fi
if [ ! -d "$BUILD" ];then
  mkdir -p "$BUILD"
else
  rm -rf "$BUILD"
  mkdir -p "$BUILD"
fi

if [ ! -d "$BUILD" ];then
  exit 1
fi
if [ ! -d "$LIB" ];then
  mkdir -p "$LIB"
else
  rm -rf "$LIB"
  mkdir -p "$LIB"
fi
if [ ! -d "$LIB" ];then
  exit 1
fi
if [ -d "$INCLUDE_INSTALL_DIR/$libname" ];then
  rm -rf "$INCLUDE_INSTALL_DIR/$libname"
  if [ $? -ne 0 ];then
    exit 1
  fi
fi
cp -a "$INC" "$INCLUDE_INSTALL_DIR/$libname"
if [ $? -ne 0 ];then
  exit 1
fi
for s in $source_files;do
  if [ -f "$s" ];then
    name="${s##*/}"
    name="${name%.*}"
    gcc -I "$INC" -c -fPIC "$s" -o "$BUILD/$name.o"
  fi
done
for o in $object_files;do
  if [ -f "$o" ];then
    objects+=("$o");
  fi
done
if [ "${#objects[@]}" -eq 0 ];then
  exit 0
fi
gcc -shared -W1,-soname,"$soname" -Wall -o "$LIB/$outputname" "${objects[@]}"
if [ -f "$LIB_INSTALL_DIR/$outputname" ];then
  rm -f "$LIB_INSTALL_DIR/$outputname"
  if [ $? -ne 0 ];then
    exit 1
  fi
fi
if [ -L "$LIB_INSTALL_DIR/$soname" ];then
  rm -f "$LIB_INSTALL_DIR/$soname"
  if [ $? -ne 0 ];then
    exit 1
  fi
fi
if [ -L "$LIB_INSTALL_DIR/$linkername" ];then
  rm -f "$LIB_INSTALL_DIR/$linkername"
  if [ $? -ne 0 ];then
    exit 1
  fi
fi
mv "$LIB/$outputname" "$LIB_INSTALL_DIR/$outputname"
if [ $? -ne 0 ];then
  exit 1
fi
ln -s "$LIB_INSTALL_DIR/$outputname" "$LIB_INSTALL_DIR/$soname"
ln -s "$LIB_INSTALL_DIR/$soname" "$LIB_INSTALL_DIR/$linkername"
exit 0
